package me.simonm34.skycore.user;

import me.simonm34.skycore.chat.ChatType;
import me.simonm34.skycore.punishments.Punishment;
import me.simonm34.skycore.rank.Rank;
import me.simonm34.skycore.sender.Sender;
import me.simonm34.skycore.warp.Warp;
import org.bukkit.GameMode;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.PlayerInventory;
import org.bukkit.scoreboard.Scoreboard;

import java.util.List;
import java.util.UUID;

public interface User extends Sender {
    Player getPlayer();
    UUID getUUID();
    String getNickname();
    PlayerInventory getInv();
    Inventory getEnderchest();
    Location getLoc();
    boolean isFlying();
    List<ItemStack> getItems();
    Scoreboard getScoreboard();
    Rank getRank();
    Rank getSubrank();
    Double getBalance();
    Warp getHome(String string);
    List<Warp> getHomes();
    List<Punishment> getPunishments();
    UUID getReply();
    UUID getTeleportRequest();
    ChatType getChat();
    UUID getSpectating();
    UUID getSpectator();
    boolean canFly();
    boolean isGodMode();
    boolean isInvsee();
    boolean isTeleporting();
    Long getChatCooldown();

    void setNickname(String string);
    void setTablistName(String string);
    void setGamemode(GameMode gamemode);
    void teleport(Location location);
    void openInv(Inventory inventory);
    void openWorkbench();
    void clearInv();
    void closeInv();
    void setScoreboard(Scoreboard scoreboard);
    void setFlySpeed();
    void setWalkSpeed();
    void setHealth(Double health);
    void hideUser(User user);
    void showUser(User user);
    void loadPerms();
    void unloadPerms();
    void setRank(Rank rank);
    void setSubrank(Rank subrank);
    void setBalance(Double balance);
    void addHome(Warp warp);
    void removeHome(Warp warp);
    void addPunishment(Punishment punishment);
    void removePunishment(Punishment punishment);
    void setReply(UUID uuid);
    void setTeleportRequest(UUID uuid);
    void setChat(ChatType chatType);
    void setSpectating(UUID uuid);
    void setSpectator(UUID uuid);
    void setCanFly(boolean canFly);
    void setGodMode(boolean godMode);
    void setIsInvsee(boolean isInvsee);
    void setTeleporting(boolean teleporting);
    void setChatCooldown(Long cooldown);
}
